theme: jekyll-theme-minimal
logo: /assets/img/296000665_579515400506877_8581069824152728106_n_circle.png
title: <center>ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ</center>
description: <center>Paul Mercier-Handisyde's CV</center>
